services:
  app:
    build:
      context: ./
    image: laravel-api
    container_name: laravel-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - laravel_network
    ports:
      - "9001:9000"
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    image: nginx:latest
    container_name: nginx_laravel
    networks:
      - laravel_network
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www

  mariadb:
    image: mariadb:latest
    container_name: mariadb_laravel
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel_network
    command: [
      '--wait_timeout=28800',
      '--bind-address=0.0.0.0',
      '--lower_case_table_names=1'
    ]

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_laravel
    links:
      - mariadb
    ports:
      - "8080:80"
    networks:
      - laravel_network
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_USER: laravel
      PMA_PASSWORD: laravel

volumes:
  mariadb_data:

networks:
  laravel_network:
    name: laravel_network
    driver: bridge
